---
title: "R Notebook"
output: html_notebook
---

```{r}
features.x <- c(1,2,3,4,7,8,9)

features.y <- c(1,2,3,4,4,3,2)

features.z <- c(1,2,3,4,4,3,2)

data <- matrix(nrow = 3, ncol = length(featuresX))

data[1,] <- features.x
data[2,] <- features.y

data

plot(featuresX, featuresY, xlab = "X", ylab = "Y")
```
```{r}
# distancia euclidiana
euclidean.distance<-function(x, y){
	resp<-sum((x-y)^2)
	resp
}

# pegando pontos mais proximos do meu K
closest.k<-function(data, centroids){
	euclidean.dist<-c()
	for(i in 1:nrow(centroids)){
		euclidean.dist[i]<-euclidean.distance(data, centroids[i,])
	}
	which.min(euclidean.dist)
}

# *************** kmeans  **************************
k.means<-function(dataset, k=2){
  # cria uma lista para receber a resposta
	resp<-list()
	cat("Inicializando centroides...\n");
	index<-sample(1:nrow(dataset), k)
	# aplica os centrois no datset
	centroids<-dataset[index, ]
  
	# 
	clustering<-rep(0,nrow(dataset))
	stop.crit<-matrix(0, nrow=nrow(centroids), ncol=ncol(centroids))

	while(euclidean.distance(stop.crit, centroids) > 0){

		#organiza os objetos em clusters iniciais
		cat("Centroides escolhidos:\n")
		for(i in 1:k){
			cat("[",i,"] = ", as.double(centroids[i,]), "\n")
		}

		for(i in 1:nrow(dataset)){
			clustering[i]<-closest.k(dataset[i,], centroids)
		}
		stop.crit<-centroids

		resp$data<-dataset
		resp$centroids<-centroids
		resp$clustering<-clustering

		#atualiza centroide...
		for(i in 1:nrow(centroids)){
			centroids[i,]<-colMeans(dataset[which(clustering == i),])
		}
	}
	resp
}
```

Execução do primeiro teste
```{r}

iris <- read.csv('../data/Iris.csv')

# pegando somente as features do meu conjunto de dados, variável contínua
iris.features <- iris[,2:3]

iris.features <- iris.features[1:10,]

iris.features

plot(iris.features$SepalLengthCm, iris.features$SepalWidthCm, xlab = "Tam Sepal", ylab = " largura Sepal")

```
```{r}
k1 <- k.means(iris.features, k=2)
print("SepalWidthCm")
k1$centroids$SepalLengthCm
print('SepalWidthCm')
k1$centroids$SepalWidthCm
```
```{r}
library(ggplot2)
library(gridExtra)
# pontos sem o agrupamento
# d1<- ggplot(iris.features, aes(SepalLengthCm, SepalWidthCm)) +
#   geom_point(size=3) 

d2<- ggplot(iris.features, aes(SepalLengthCm, SepalWidthCm, color = k1$clustering)) +
     geom_point(size=3) + theme(legend.position="none")
d2

# # + geom_rug()
# 
# # agrupado com o kmeans
# d2<- ggplot(iris.features, aes(SepalLengthCm, SepalWidthCm, color = k1$clustering)) +
#     geom_point(size=3) + theme(legend.position="none")
# 
# d3<- ggplot(k1$centroids, aes(SepalLengthCm, SepalWidthCm, color = c(1,6))) +
#     geom_point(size=4) + theme(legend.position="none")
# 
# grid.arrange(d1, d2, d3, ncol=3)

```

# resto

# Base
```{python, engine.path = '/usr/bin/python3'}
#import matplotlib.pyplot as plt
#import seaborn as sns; sns.set()  # for plot styling
#import numpy as np
#plt.scatter(x, y)
#plt.title(' Relaçao')
```

